spring:
   jpa:
      open-in-view: false
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         jdbc.lob.non_contextual_creation: true
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: update

---
profile: local

spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/liquibase
      username: postgres
      password: postgres