spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
  datasource:
    continue-on-error: false

---
profile: local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cap
    username: postgres
    password: postgres

endpoints:
  shutdown:
    enabled: true
    sensitive: false
