/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Product,
    ProductFromJSON,
    ProductToJSON,
    ProductEntity,
    ProductEntityFromJSON,
    ProductEntityToJSON,
} from '../models';

export interface CreateOrUpdateUsingPOSTRequest {
    entities: Array<ProductEntity>;
}

export interface DeleteByIdUsingPOSTRequest {
    idList: Array<string>;
}

export interface GetAllUsingGETRequest {
    pageNumber?: number;
    size?: number;
}

export interface GetByIdUsingPOSTRequest {
    idList: Array<string>;
}

/**
 * 
 */
export class ProductResourceApi extends runtime.BaseAPI {

    /**
     * createOrUpdate
     */
    async createOrUpdateUsingPOSTRaw(requestParameters: CreateOrUpdateUsingPOSTRequest): Promise<runtime.ApiResponse<Array<Product>>> {
        if (requestParameters.entities === null || requestParameters.entities === undefined) {
            throw new runtime.RequiredError('entities','Required parameter requestParameters.entities was null or undefined when calling createOrUpdateUsingPOST.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/product/create-or-update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.entities.map(ProductEntityToJSON),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * createOrUpdate
     */
    async createOrUpdateUsingPOST(requestParameters: CreateOrUpdateUsingPOSTRequest): Promise<Array<Product>> {
        const response = await this.createOrUpdateUsingPOSTRaw(requestParameters);
        return await response.value();
    }

    /**
     * deleteById
     */
    async deleteByIdUsingPOSTRaw(requestParameters: DeleteByIdUsingPOSTRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.idList === null || requestParameters.idList === undefined) {
            throw new runtime.RequiredError('idList','Required parameter requestParameters.idList was null or undefined when calling deleteByIdUsingPOST.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/product/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.idList,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteById
     */
    async deleteByIdUsingPOST(requestParameters: DeleteByIdUsingPOSTRequest): Promise<void> {
        await this.deleteByIdUsingPOSTRaw(requestParameters);
    }

    /**
     * getAll
     */
    async getAllUsingGETRaw(requestParameters: GetAllUsingGETRequest): Promise<runtime.ApiResponse<Array<Product>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['pageNumber'] = requestParameters.pageNumber;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/product/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * getAll
     */
    async getAllUsingGET(requestParameters: GetAllUsingGETRequest): Promise<Array<Product>> {
        const response = await this.getAllUsingGETRaw(requestParameters);
        return await response.value();
    }

    /**
     * getById
     */
    async getByIdUsingPOSTRaw(requestParameters: GetByIdUsingPOSTRequest): Promise<runtime.ApiResponse<Array<Product>>> {
        if (requestParameters.idList === null || requestParameters.idList === undefined) {
            throw new runtime.RequiredError('idList','Required parameter requestParameters.idList was null or undefined when calling getByIdUsingPOST.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/product/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.idList,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * getById
     */
    async getByIdUsingPOST(requestParameters: GetByIdUsingPOSTRequest): Promise<Array<Product>> {
        const response = await this.getByIdUsingPOSTRaw(requestParameters);
        return await response.value();
    }

}
