/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cap.backend.entity;

import java.util.Objects;
import java.util.Arrays;
import com.cap.backend.entity.IngredientEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ProductEntity
 */

public class ProductEntity {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_FULL_IMAGE_URL = "fullImageUrl";
  @SerializedName(SERIALIZED_NAME_FULL_IMAGE_URL)
  private String fullImageUrl;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_INGREDIENTS = "ingredients";
  @SerializedName(SERIALIZED_NAME_INGREDIENTS)
  private List<IngredientEntity> ingredients = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUPPLIER_ID = "supplierId";
  @SerializedName(SERIALIZED_NAME_SUPPLIER_ID)
  private String supplierId;

  public static final String SERIALIZED_NAME_THUMBNAIL_URL = "thumbnailUrl";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL_URL)
  private String thumbnailUrl;


  public ProductEntity description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ProductEntity fullImageUrl(String fullImageUrl) {
    
    this.fullImageUrl = fullImageUrl;
    return this;
  }

   /**
   * Get fullImageUrl
   * @return fullImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFullImageUrl() {
    return fullImageUrl;
  }


  public void setFullImageUrl(String fullImageUrl) {
    this.fullImageUrl = fullImageUrl;
  }


  public ProductEntity id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ProductEntity ingredients(List<IngredientEntity> ingredients) {
    
    this.ingredients = ingredients;
    return this;
  }

  public ProductEntity addIngredientsItem(IngredientEntity ingredientsItem) {
    if (this.ingredients == null) {
      this.ingredients = new ArrayList<IngredientEntity>();
    }
    this.ingredients.add(ingredientsItem);
    return this;
  }

   /**
   * Get ingredients
   * @return ingredients
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<IngredientEntity> getIngredients() {
    return ingredients;
  }


  public void setIngredients(List<IngredientEntity> ingredients) {
    this.ingredients = ingredients;
  }


  public ProductEntity name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ProductEntity supplierId(String supplierId) {
    
    this.supplierId = supplierId;
    return this;
  }

   /**
   * Get supplierId
   * @return supplierId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSupplierId() {
    return supplierId;
  }


  public void setSupplierId(String supplierId) {
    this.supplierId = supplierId;
  }


  public ProductEntity thumbnailUrl(String thumbnailUrl) {
    
    this.thumbnailUrl = thumbnailUrl;
    return this;
  }

   /**
   * Get thumbnailUrl
   * @return thumbnailUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getThumbnailUrl() {
    return thumbnailUrl;
  }


  public void setThumbnailUrl(String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductEntity productEntity = (ProductEntity) o;
    return Objects.equals(this.description, productEntity.description) &&
        Objects.equals(this.fullImageUrl, productEntity.fullImageUrl) &&
        Objects.equals(this.id, productEntity.id) &&
        Objects.equals(this.ingredients, productEntity.ingredients) &&
        Objects.equals(this.name, productEntity.name) &&
        Objects.equals(this.supplierId, productEntity.supplierId) &&
        Objects.equals(this.thumbnailUrl, productEntity.thumbnailUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, fullImageUrl, id, ingredients, name, supplierId, thumbnailUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductEntity {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fullImageUrl: ").append(toIndentedString(fullImageUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ingredients: ").append(toIndentedString(ingredients)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supplierId: ").append(toIndentedString(supplierId)).append("\n");
    sb.append("    thumbnailUrl: ").append(toIndentedString(thumbnailUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

