---
version: '3'

services:
    application:
      image: ${APPLICATION_IMAGE}:${APPLICATION_VERSION}
      container_name: ${APPLICATION_NAME}
      hostname: ${APPLICATION_NAME}
      depends_on:
        - mongodb
      networks:
        - application_net
      ports:
          - 8080:8080
          - 9010:9010
