spring:
   datasource:
      # database connection parameters
      url: jdbc:postgresql://localhost:5432/hibernate_liquibase
      
   jpa:
      open-in-view: false
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         jdbc.lob.non_contextual_creation: true
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.hbm2ddl.auto: update

# liquibase change log file
liquibase:
   change-log: classpath:db/db.changelog-master.yaml

---
profile: local

spring:
   datasource:
      username: postgres
      password: postgres
   
   h2.console.enabled: true