/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientEntity
 */
export interface IngredientEntity {
    /**
     * 
     * @type {string}
     * @memberof IngredientEntity
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientEntity
     */
    fullImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientEntity
     */
    thumbnailUrl?: string;
}

export function IngredientEntityFromJSON(json: any): IngredientEntity {
    return IngredientEntityFromJSONTyped(json, false);
}

export function IngredientEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fullImageUrl': !exists(json, 'fullImageUrl') ? undefined : json['fullImageUrl'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'thumbnailUrl': !exists(json, 'thumbnailUrl') ? undefined : json['thumbnailUrl'],
    };
}

export function IngredientEntityToJSON(value?: IngredientEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'fullImageUrl': value.fullImageUrl,
        'name': value.name,
        'thumbnailUrl': value.thumbnailUrl,
    };
}


