/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IngredientEntity,
    IngredientEntityFromJSON,
    IngredientEntityFromJSONTyped,
    IngredientEntityToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductEntity
 */
export interface ProductEntity {
    /**
     * 
     * @type {string}
     * @memberof ProductEntity
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEntity
     */
    fullImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEntity
     */
    id?: string;
    /**
     * 
     * @type {Array<IngredientEntity>}
     * @memberof ProductEntity
     */
    ingredients?: Array<IngredientEntity>;
    /**
     * 
     * @type {string}
     * @memberof ProductEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEntity
     */
    supplierId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEntity
     */
    thumbnailUrl?: string;
}

export function ProductEntityFromJSON(json: any): ProductEntity {
    return ProductEntityFromJSONTyped(json, false);
}

export function ProductEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fullImageUrl': !exists(json, 'fullImageUrl') ? undefined : json['fullImageUrl'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ingredients': !exists(json, 'ingredients') ? undefined : ((json['ingredients'] as Array<any>).map(IngredientEntityFromJSON)),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'supplierId': !exists(json, 'supplierId') ? undefined : json['supplierId'],
        'thumbnailUrl': !exists(json, 'thumbnailUrl') ? undefined : json['thumbnailUrl'],
    };
}

export function ProductEntityToJSON(value?: ProductEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'fullImageUrl': value.fullImageUrl,
        'id': value.id,
        'ingredients': value.ingredients === undefined ? undefined : ((value.ingredients as Array<any>).map(IngredientEntityToJSON)),
        'name': value.name,
        'supplierId': value.supplierId,
        'thumbnailUrl': value.thumbnailUrl,
    };
}


